### ISSUE TITLE
Simpler Iteration

### ISSUE THREAD

**Issue by billkouts** [DahlitzFlorian/why-you-should-use-more-enums-in-python-article-snippets#2]
Hello!
I was going through your article and I saw the iteration example. 
Do you think there is any benefit using your approach instead of a simpler iteration like the one demonstrated [here](https://github.com/DahlitzFlorian/why-you-should-use-more-enums-in-python-article-snippets/pull/1) ?
To be fair, I have seen the same suggestion in multiple mini tutorials, so I am convinced that there might be a reason for it

**Comment by DahlitzFlorian** [comment]
Hello @billkouts!
First of all, thanks for your interest and asking the question. Indeed, there is a reason why I used `__members__`. You are right, in the example at hand both iterations produce the same result, but consider the following example:

```python
from enum import Enum


class Colour(Enum):
    BLUE = 1
    GREEN = 2
    RED = 3
    ALIAS_BLUE = 1
```

You can define aliases for certain values. In this case, I defined an alias for the value `1`. Iterating over the `Colour` enum produces:

```python
>>> for member in Colour:
...    print(member.name, member)
...
BLUE Colour.BLUE
GREEN Colour.GREEN
RED Colour.RED
```

... whereas iterating over the `__members__` mapping produces:

```python
>>> for name, member in Colour.__members__.items():
...     print(name, member)
...
BLUE Colour.BLUE
GREEN Colour.GREEN
RED Colour.RED
ALIAS_BLUE Colour.BLUE
```

As you can see, the latter includes aliases whereas the first one does not. So if you want to make sure that aliases are included, use the read-only `__members__` mapping, which is a convenience mapping giving you all names defined for all values.

Reference: https://docs.python.org/3/library/enum.html#iteration
